spring.application.name=delivery-api


# Porta do servidor
server.port=8080

# Configuração H2 (banco em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Console H2 (para visualizar dados)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console